# -*- coding: utf-8 -*-
"""NLP using streamlit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Nsd22U1DX514AjbrHWY14-bhmW3BQFRu
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install -q streamlit \langdetect pyspellchecker \ nltk langcodes deep-translator

from nltk.tokenize import word_tokenize

from langdetect import DetectorFactory
DetectorFactory.seed = 0

from spellchecker import SpellChecker
from nltk.tokenize.treebank import TreebankWordDetokenizer

from langdetect import detect

from deep_translator import GoogleTranslator

import re

SPELL_LANGS = {"en","es","fr","pt","de",
"ru","ar","eu","lv","nl"}

TARGET_LANGS = {
"Tiếng Việt": "vi", "Tiếng Anh": "en",
"Tiếng Pháp": "fr", "Tiếng Nhật": "ja",
"Tiếng Trung (Giản thể)": "zh-CN",
"Tiếng Hàn": "ko", "Tiếng Đức": "de"}

import nltk

# Tải gói dữ liệu punkt_tab
nltk.download('punkt_tab')

def requirement(text):
  if len(text) <3 :
    print("Error: Too short")
    return None

  language_predict= detect(text)
  if language_predict != "en":
    print("Error: Language not supported")
    return None

  return text

def spell_check(text):
  spell = SpellChecker()
  checked_text=requirement(text)
  if checked_text is None:
    return "Error, pls write another example"

  pattern = r"https?://[^\s]+|[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}|#[a-zA-Z0-9_]+|\d+:\d+(?:[a-zA-Z]+)?|\w+'\w+|[a-zA-Z]+|\d+|[^\w\s]"
  sentences=re.findall(pattern, text)
  final_corrected_text= []
  for word in sentences:
    if word.startswith("#") or "@" or "https" in word:
      final_corrected_text.append(word)
      continue
    if word.isalpha() and len(word) > 1 :
      word=spell.correction(word) or word
      final_corrected_text.append(word)
    else:
      final_corrected_text.append(word)

  final_corrected_text= TreebankWordDetokenizer().detokenize(final_corrected_text)
  return final_corrected_text


Ex_test = "I'm REALLYYY excited for the NEXXT meeting at 9:00AM with Dr.John (john.doe@example.com)!! #nlp #SpellCheck"
#print(spell_check(Ex_test))

Ex2_test="Dr.O'Connor's 10.5-inch iPad (costing $999.99/ea) won't sync via https://apple.com/support @ 9:30AM... isn't that #CRAZZZY?! #TechSupport2026"
print(spell_check(Ex2_test))

def run_translation(text,tar_lan):
  language_predict= detect(text)
  if language_predict == "en":
    raw_text= spell_check(text)
  else:
    raw_text= text

  target_lang_code = TARGET_LANGS[tar_lan]
  if target_lang_code not in SPELL_LANGS:
    return "Ko hỗ trợ ngôn ngữ này"

  try:
    translator = GoogleTranslator(
      source="auto",
      target=target_lang_code
    )
    translated = translator.translate(raw_text)
    return translated

  except Exception as e:
    return "Error: " + str(e)

test_text_1 = """
Thử nghiệm:
1. Khi 'users' đăng nhập, hàm `get_user_data()` sẽ trả về:
{"status": 200, "message": "OK", "data": null}.
2. URL: https://example.com/api/v1/checkout?item_id=10293
3. Ký tự đặc biệt: #HashTag_2026, @mention, $100USD, &amp;
4. Văn bản chêm tiếng Nhật: こんにちは (Konnichiwa) - Xin chào!
"""

translated_1 = run_translation(test_text_1,"Tiếng Anh")
print(translated_1)

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# 
# 
# import streamlit as st
# from nltk.tokenize import word_tokenize
# from langdetect import DetectorFactory
# DetectorFactory.seed = 0
# from spellchecker import SpellChecker
# from nltk.tokenize.treebank import TreebankWordDetokenizer
# from langdetect import detect
# from deep_translator import GoogleTranslator
# import re
# import nltk
# # Tải gói dữ liệu punkt_tab
# nltk.download('punkt_tab')
# 
# SPELL_LANGS = {"en","es","fr","pt","de",
# "ru","ar","eu","lv","nl"}
# 
# TARGET_LANGS = {
# "Tiếng Việt": "vi", "Tiếng Anh": "en",
# "Tiếng Pháp": "fr", "Tiếng Nhật": "ja",
# "Tiếng Trung (Giản thể)": "zh-CN",
# "Tiếng Hàn": "ko", "Tiếng Đức": "de"}
# 
# ###########################################################################
# def requirement(text):
#   if len(text) <3 :
#     print("Error: Too short")
#     return None
# 
#   language_predict= detect(text)
#   if language_predict != "en":
#     print("Error: Language not supported")
#     return None
# 
#   return text
# 
# def spell_check(text):
#   spell = SpellChecker()
#   checked_text=requirement(text)
#   if checked_text is None:
#     return "Error, pls write another example"
# 
#   pattern = r"https?://[^\s]+|[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}|#[a-zA-Z0-9_]+|\d+:\d+(?:[a-zA-Z]+)?|\w+'\w+|[a-zA-Z]+|\d+|[^\w\s]"
#   sentences=re.findall(pattern, text)
#   final_corrected_text= []
#   for word in sentences:
#     if word.isalpha() and len(word) > 1 :
#       word=spell.correction(word) or word
#       final_corrected_text.append(word)
#     else:
#       final_corrected_text.append(word)
# 
#   final_corrected_text= TreebankWordDetokenizer().detokenize(final_corrected_text)
#   return final_corrected_text
# 
# def run_translation(text,tar_lan):
#   language_predict= detect(text)
#   if language_predict == "en":
#     raw_text= spell_check(text)
#   else:
#     raw_text= text
# 
#   target_lang_code = TARGET_LANGS[tar_lan] if tar_lan in TARGET_LANGS else None
#   if target_lang_code is None:
#     return "Ko hỗ trợ ngôn ngữ này"
# 
#   try:
#     translator = GoogleTranslator(
#       source="auto",
#       target=target_lang_code
#     )
#     translated = translator.translate(raw_text)
#     return translated
# 
#   except Exception as e:
#     return "Error: " + str(e)
# 
# 
# ###########################################################################
# st.set_page_config(page_title="NLP Pipeline Demo", layout="centered")
# st.title("Streamlit NLP Pipeline Demo")
# st.caption("Hai ứng dụng: Dịch văn bản · Sửa lỗi chính tả")
# tab_t, tab_s = st.tabs(["Dịch văn bản", "Sửa lỗi chính tả"])
# with tab_t:
#   input_text=st.text_area("Nhập văn bản cần dịch", height=200)
#   input_language=st.text_input("Ngôn ngữ đích")
#   if "input_text" not in st.session_state:
#     st.session_state.input_text = []
#   if "input_languag" not in st.session_state:
#     st.session_state.input_language = []
# 
#   if st.button("Dịch"):
#     translated_text=run_translation(input_text,input_language)
#     st.write(translated_text)
#   with st.expander("Ví dụ"):
#     with st.container(border=True):
#       st.write("こんにちは、お名前は何ですか")
# 
#     st.write("Hallo, wie heißt du?")
# 
# with tab_s:
#   corrected_input_text=st.text_area("Nhập văn bản cần sửa", height=200)
#   if "corrected_input_text" not in st.session_state:
#     st.session_state.corrected_input_text = []
#   if st.button("Sửa"):
#     corrected_text=spell_check(corrected_input_text)
#     st.write(corrected_text)
#   with st.expander("Ví dụ"):
#     with st.container(border=True):
#       st.write("I'm REALLYYY excited for the NEXXT meeting at 9:00AM with Dr.John (john.doe@example.com)!! #nlp #SpellCheck")
# 
#     st.write("I'm really excited for the next meeting at 9:00AM with Dr . John (john.doe@example.com)!! #nlp #SpellCheck")
# 
#

!streamlit run app.py --server.enableCORS false --server.enableXsrfProtection false >/tmp/streamlit.log 2>&1 &
!sleep 5 && tail -n 20 /tmp/streamlit.log

!wget -q -O cloudflared https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
!chmod +x cloudflared
!./cloudflared tunnel --url http://localhost:8501